### ISSUE TITLE
Theme: Chess.com

### ISSUE THREAD

**Issue by LudamStudio** [algertc/prettierlichess-themes#1]
![image](https://user-images.githubusercontent.com/71848144/114755398-3396cd00-9d1f-11eb-8aa3-fc3bbefaa47b.png)

[chesscom.zip](https://github.com/algertc/prettierlichess-themes/files/6312727/chesscom.zip)

**Comment by algertc** [comment]
Thank you for your submission. I will add this, but please use a pull request instead of issue for adding new themes.
