### ISSUE TITLE
Cant use any theme, just the default

### ISSUE THREAD

**Issue by 9acca9** [algertc/prettierlichess-themes#6]
hi.
im trying prettierlichess and... is really pretty! But, i cant use any of the theme. I download the json file and import from extension icon.
But, nothing change. 
Im using Chrome, in Manjaro Linux.
Thanks.

**Comment by algertc** [comment]
I just tested it and it seems to be working fine. Are you sure that you have the json downloaded correctly and in the correct format. Could you upload a screenshot of what you are experiencing?

**Comment by 9acca9** [comment]
The json is fine. I try now in Firefox and in there you have the past the code. And it works.
But, it will be nice if works in Chrome, that for me is not working, because i use the sound "speech" that seems to work just in Chrome.

In Chrome the json is imported (without paste, i mean, an openbox to select the json file pop up). When i import nothing happens.

![image](https://user-images.githubusercontent.com/25393371/233760618-addfaa83-86bf-4e6b-93ac-097878188280.png)

The is not much to show. I select the file, and dont work. 
I could try other thing?
Thanks!

**Comment by 9acca9** [comment]
is working in firefox. So, all ok.

**Comment by kieferro** [comment]
> is working in firefox. So, all ok.

I'm glad to hear that. If you still have similar problems, feel free to open an issue in the official [Prettierlichess repo](https://github.com/prettierlichess/prettierlichess/). This is just the collection for the themes, but the extension code is there and bugs can be reported there as well.
